en:
  languageName: EN
  languageCode: en-US
  disabled: false
  weight: 1
zh:
  languageName: 中
  languageCode: zh-CN
  disabled: false
  weight: 2
  author: Ladder 主题
  authorDescription: 一个美观，快速并且专注于阅读的主题
  info: 帮助开发者构建一个免费并且漂亮的博客网站，记录自己的思考并且提高自己的影响力
  #guestbook:
  #  title: 留言板
  #  description: 您的评论，会让该网站更精彩！
  menu:
    main:
      - name: 文章
        url: /blog
        weight: 1
      - name: 生活
        url: /art
        weight: 2
      - name: 标签
        url: /tags
        weight: 3
      - name: 历史
        url: /archives
        weight: 4
      #- name: 留言板
      #  url: /guestbook
      #  weight: 4
      - name: 统计
        url: https://umami-five-ruby.vercel.app/share/LZBeTsMNrOU5Jtdc/vacat.github.io
        weight: 5
#zh:
#  languageName: 中
#  author: Ladder 主题
#  authorDescription: 一个美观，快速并且专注于阅读的主题
#  info: 帮助开发者构建一个免费并且漂亮的博客网站，记录自己的思考并且提高自己的影响力